language: ruby
rvm:
- 2.1
script:
- rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAJUHCKKZCTVJQGOXA
  secret_access_key:
    secure: JqgqPebaI6aoplctpz3y6baGbi9PEjv8MLZWb/fXPWIWmq1jHfU/mLM5gUAT0N41qqcKT9JtrUD5ybG8EyKaczt/z5CHUR+K0DkVVc0wiKiM5+Ow+XAK40ZamZj+pRgHy8hhPLqcVjuZp1DEzM6MgfJ7RQ7n7AJXbdRlal511Ug=
  bucket: www.jacobtomlinson.co.uk
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  on:
    repo: jacobtomlinson/jacobtomlinson.github.io
    branch: s3-deploy
