baseURL = "https://jacobtomlinson.dev"
disqusShortname = "jacobtomlinson"
googleAnalytics = "UA-20365477-2"
languageCode = "en-gb"
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "working"
title = "Jacob Tomlinson"

[params]
SiteSourceURL = "https://github.com/jacobtomlinson/website"
author = "Jacob Tomlinson"
avatar = "https://github.com/jacobtomlinson.png"
description = "Building [RAPIDS](https://rapids.ai/) and [Dask](https://dask.org/) at [NVIDIA](https://nvidia.com/). Tinker with [Opsdroid](https://opsdroid.dev/) in my spare time. he/him."
images = ["https://2.gravatar.com/avatar/b7c2d49748426791dc98b8214dfac9d1?s=500"]
twitter = "https://twitter.com/_jacobtomlinson"

footer_left = "Made with <i class=\"fa fa-heart\"></i> using [Hugo](https://gohugo.io/)</a>"
footer_right = "<i class=\"fa fa-code\"></i> on [Github](https://github.com/jacobtomlinson/jacobtomlinson.github.io) &nbsp;<i class=\"fab fa-github-alt\"></i>"

[permalinks]
posts = "/:section/:year/:title/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[outputFormats]
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"

[markup.goldmark.renderer]
unsafe = true
