baseURL = "https://jacobtomlinson.dev"
disqusShortname = "jacobtomlinson"
enableRobotsTXT = true
googleAnalytics = "UA-20365477-2"
languageCode = "en-gb"
pygmentsCodeFences = true
pygmentsUseClasses = true
summaryLength = 15
theme = "working"
title = "Jacob Tomlinson"

[params]
SiteSourceURL = "https://github.com/jacobtomlinson/website"
author = "Jacob Tomlinson"
avatar = "/profile-thumb.png"
description = "Building RAPIDS and Dask at NVIDIA. Tinker with Opsdroid in my spare time. he/him."
github = "https://github.com/jacobtomlinson"
images = ["https://i.imgur.com/Ln3NJU2h.png"]
twitter = "https://twitter.com/_jacobtomlinson"
bluesky_handle = "jacobtomlinson.dev"
bluesky = "https://bsky.app/profile/jacobtomlinson.dev"

footer_left = "Made with <i class=\"fa fa-heart\"></i> using [Hugo](https://gohugo.io/)</a>"
footer_right = "<i class=\"fa fa-code\"></i> on [Github](https://github.com/jacobtomlinson/jacobtomlinson.github.io) &nbsp;<i class=\"fab fa-github-alt\"></i>"

[permalinks]
posts = "/:section/:year/:title/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[outputFormats]
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"
[outputFormats.email]
baseName = "email"
isHTML = true
isPlainText = true
mediatype = "text/html"
name = "email"
noUgly = true
permalinkable = false

[outputs]
page = ['HTML', 'RSS', 'email']

[markup.goldmark.renderer]
unsafe = true
